import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";
import { cn } from "@/lib/utils";
import Leftbar from "@/MyComponent/sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import Header from "@/MyComponent/header";
import { Providers } from "@/provider/Providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
          <Providers>
            <SidebarProvider>
              <Leftbar />
              <main className="px-(--main-page-padding-x) w-full">

                {/* <SidebarTrigger /> */}
                <Header />
                <div className="mt-8">{children}</div>
              </main>
            </SidebarProvider>
          </Providers>
         
      </body>
    </html>
  );
}
